//Auth reducer types
export const AUTHENTICATE = "AUTHENTICATE";
export const LOGOUT = "LOGOUT";
export const SET_USERPROFILE = "SET_USERPROFILE";
//Data reducer types
export const SET_CUSTOMERS = "SET_CUSTOMERS";
export const SET_REMOVE_CUSTOMERS = "SET_REMOVE_CUSTOMERS";
export const SET_ACTIVE_CUSTOMER = "SET_ACTIVE_CUSTOMER";
export const RESET_ACTIVE_CUSTOMER = "RESET_ACTIVE_CUSTOMER";
export const SET_TRIP = "SET_TRIP";
export const SET_COMMISSION = "SET_COMMISSION";
export const SET_ON_TRIP = "SET_ON_TRIP";
export const SET_TRIP_STATUS = "SET_TRIP_STATUS";
export const SET_OFF_TRIP = "SET_OFF_TRIP";
export const RESETUSER = "RESETUSER";
export const SET_DRUNKEN_STATUS = "SET_DRUNKEN_STATUS";
export const SET_DRUNKEN_STATUS_LOCAL = "SET_DRUNKEN_STATUS_LOCAL";
export const SET_DRIVER_STATUS = "SET_DRIVER_STATUS";
export const LOADING_DATA = "LOADING_DATA";

